[project]
name = "webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "chardet>=5.2.0",
    "duckdb>=1.2.2",
    "faicons>=0.2.2",
    "fastparquet>=2024.11.0",
    "ipykernel>=6.29.5",
    "jinja2>=3.1.6",
    "matplotlib>=3.10.1",
    "missingno>=0.5.2",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "pvlib>=0.12.0",
    "pyarrow>=20.0.0",
    "pytz>=2025.2",
    "shiny>=1.4.0",
    "shinyswatch>=0.9.0",
    "shinywidgets>=0.5.2",
]
